server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://14.103.49.81:33060/hiolabsdb?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: ^tPT4DwgTX9cKyOm
#    url: jdbc:mysql://127.0.0.1:3306/hiolabsdb?useSSL=false&characterEncoding=utf8&serverTimezone=UTC
#    username: root
#    password: bjm152689.
    druid:
      # Druid ??
      initial-size: 5       # ??????
      min-idle: 5           # ??????
      max-active: 20        # ?????
      max-wait: 60000       # ??????????
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      # ????????
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin123
        reset-enable: false

      # ?? Web ????????
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"

  data:
    redis:
      host: 14.103.49.81
      port: 6172
      password: ^tPT4DwgTX9cKyOm
  security:
    ignore-urls:
      - /swagger-ui/**
      - /swagger-resources/**
      - /webjars/**
      - /doc.html
      - /favicon.ico
      - /v3/api-docs/**
      - /static/**
      - /resources/**
      - /auth/code
      - /verify
      - /**
  jwt:
    security-key: 3F4428472B4B6250655368566D5971337336763979244226452948404D635166
    expire: 2592000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.liyuyouguo.entity
#  configuration:
#    # ????
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.liyuyouguo

fruit-shop:
  appid: wx7af111110000000
  secret: cb8e5adce569f9bddce5b8123123e1115aaddce505